// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core/network/protobuf/proto_src/game.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_NONE  Direction = 0
	Direction_LEFT  Direction = 1
	Direction_RIGHT Direction = 2
	Direction_UP    Direction = 3
	Direction_DOWN  Direction = 4
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "NONE",
		1: "LEFT",
		2: "RIGHT",
		3: "UP",
		4: "DOWN",
	}
	Direction_value = map[string]int32{
		"NONE":  0,
		"LEFT":  1,
		"RIGHT": 2,
		"UP":    3,
		"DOWN":  4,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_core_network_protobuf_proto_src_game_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_core_network_protobuf_proto_src_game_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{0}
}

type MoveAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           Direction              `protobuf:"varint,1,opt,name=dir,proto3,enum=proto.Direction" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveAction) Reset() {
	*x = MoveAction{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveAction) ProtoMessage() {}

func (x *MoveAction) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveAction.ProtoReflect.Descriptor instead.
func (*MoveAction) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{0}
}

func (x *MoveAction) GetDir() Direction {
	if x != nil {
		return x.Dir
	}
	return Direction_NONE
}

type ShootAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shoot target coordinates
	Target        *Position `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShootAction) Reset() {
	*x = ShootAction{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShootAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootAction) ProtoMessage() {}

func (x *ShootAction) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootAction.ProtoReflect.Descriptor instead.
func (*ShootAction) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{1}
}

func (x *ShootAction) GetTarget() *Position {
	if x != nil {
		return x.Target
	}
	return nil
}

type PlayerAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*PlayerAction_Move
	//	*PlayerAction_Shoot
	Action        isPlayerAction_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerAction) GetAction() isPlayerAction_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *PlayerAction) GetMove() *MoveAction {
	if x != nil {
		if x, ok := x.Action.(*PlayerAction_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *PlayerAction) GetShoot() *ShootAction {
	if x != nil {
		if x, ok := x.Action.(*PlayerAction_Shoot); ok {
			return x.Shoot
		}
	}
	return nil
}

type isPlayerAction_Action interface {
	isPlayerAction_Action()
}

type PlayerAction_Move struct {
	Move *MoveAction `protobuf:"bytes,1,opt,name=move,proto3,oneof"`
}

type PlayerAction_Shoot struct {
	Shoot *ShootAction `protobuf:"bytes,2,opt,name=shoot,proto3,oneof"`
}

func (*PlayerAction_Move) isPlayerAction_Action() {}

func (*PlayerAction_Shoot) isPlayerAction_Action() {}

type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerActions []*PlayerAction        `protobuf:"bytes,1,rep,name=player_actions,json=playerActions,proto3" json:"player_actions,omitempty"`
	PlayerId      uint32                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInput) GetPlayerActions() []*PlayerAction {
	if x != nil {
		return x.PlayerActions
	}
	return nil
}

func (x *PlayerInput) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{4}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Position              `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Health        float32                `protobuf:"fixed32,2,opt,name=health,proto3" json:"health,omitempty"`
	PlayerId      uint32                 `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerState) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PlayerState) GetHealth() float32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PlayerState) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type BulletState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Position              `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Size          float32                `protobuf:"fixed32,2,opt,name=size,proto3" json:"size,omitempty"`
	OwnerId       uint32                 `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletState) Reset() {
	*x = BulletState{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletState) ProtoMessage() {}

func (x *BulletState) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletState.ProtoReflect.Descriptor instead.
func (*BulletState) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{6}
}

func (x *BulletState) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *BulletState) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BulletState) GetOwnerId() uint32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type WorldState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickNum       uint32                 `protobuf:"varint,1,opt,name=tick_num,json=tickNum,proto3" json:"tick_num,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Bullets       []*BulletState         `protobuf:"bytes,3,rep,name=bullets,proto3" json:"bullets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldState) Reset() {
	*x = WorldState{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldState) ProtoMessage() {}

func (x *WorldState) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldState.ProtoReflect.Descriptor instead.
func (*WorldState) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{7}
}

func (x *WorldState) GetTickNum() uint32 {
	if x != nil {
		return x.TickNum
	}
	return 0
}

func (x *WorldState) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *WorldState) GetBullets() []*BulletState {
	if x != nil {
		return x.Bullets
	}
	return nil
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameName      string                 `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

type ConnectAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectAck) Reset() {
	*x = ConnectAck{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAck) ProtoMessage() {}

func (x *ConnectAck) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAck.ProtoReflect.Descriptor instead.
func (*ConnectAck) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectAck) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type DeathNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeathNote) Reset() {
	*x = DeathNote{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeathNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeathNote) ProtoMessage() {}

func (x *DeathNote) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeathNote.ProtoReflect.Descriptor instead.
func (*DeathNote) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{10}
}

func (x *DeathNote) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ReconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPlayerId   uint32                 `protobuf:"varint,1,opt,name=old_player_id,json=oldPlayerId,proto3" json:"old_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectRequest) Reset() {
	*x = ReconnectRequest{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectRequest) ProtoMessage() {}

func (x *ReconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectRequest.ProtoReflect.Descriptor instead.
func (*ReconnectRequest) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{11}
}

func (x *ReconnectRequest) GetOldPlayerId() uint32 {
	if x != nil {
		return x.OldPlayerId
	}
	return 0
}

type GameMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameMessage_World
	//	*GameMessage_PlayerInput
	//	*GameMessage_ConnectRequest
	//	*GameMessage_ReconnectRequest
	//	*GameMessage_ConnectAck
	//	*GameMessage_DeathNote
	Payload       isGameMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_network_protobuf_proto_src_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_core_network_protobuf_proto_src_game_proto_rawDescGZIP(), []int{12}
}

func (x *GameMessage) GetPayload() isGameMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessage) GetWorld() *WorldState {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_World); ok {
			return x.World
		}
	}
	return nil
}

func (x *GameMessage) GetPlayerInput() *PlayerInput {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_PlayerInput); ok {
			return x.PlayerInput
		}
	}
	return nil
}

func (x *GameMessage) GetConnectRequest() *ConnectRequest {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_ConnectRequest); ok {
			return x.ConnectRequest
		}
	}
	return nil
}

func (x *GameMessage) GetReconnectRequest() *ReconnectRequest {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_ReconnectRequest); ok {
			return x.ReconnectRequest
		}
	}
	return nil
}

func (x *GameMessage) GetConnectAck() *ConnectAck {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_ConnectAck); ok {
			return x.ConnectAck
		}
	}
	return nil
}

func (x *GameMessage) GetDeathNote() *DeathNote {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_DeathNote); ok {
			return x.DeathNote
		}
	}
	return nil
}

type isGameMessage_Payload interface {
	isGameMessage_Payload()
}

type GameMessage_World struct {
	World *WorldState `protobuf:"bytes,1,opt,name=world,proto3,oneof"`
}

type GameMessage_PlayerInput struct {
	PlayerInput *PlayerInput `protobuf:"bytes,2,opt,name=player_input,json=playerInput,proto3,oneof"`
}

type GameMessage_ConnectRequest struct {
	ConnectRequest *ConnectRequest `protobuf:"bytes,3,opt,name=connect_request,json=connectRequest,proto3,oneof"`
}

type GameMessage_ReconnectRequest struct {
	ReconnectRequest *ReconnectRequest `protobuf:"bytes,4,opt,name=reconnect_request,json=reconnectRequest,proto3,oneof"`
}

type GameMessage_ConnectAck struct {
	ConnectAck *ConnectAck `protobuf:"bytes,5,opt,name=connect_ack,json=connectAck,proto3,oneof"`
}

type GameMessage_DeathNote struct {
	DeathNote *DeathNote `protobuf:"bytes,6,opt,name=death_note,json=deathNote,proto3,oneof"`
}

func (*GameMessage_World) isGameMessage_Payload() {}

func (*GameMessage_PlayerInput) isGameMessage_Payload() {}

func (*GameMessage_ConnectRequest) isGameMessage_Payload() {}

func (*GameMessage_ReconnectRequest) isGameMessage_Payload() {}

func (*GameMessage_ConnectAck) isGameMessage_Payload() {}

func (*GameMessage_DeathNote) isGameMessage_Payload() {}

var File_core_network_protobuf_proto_src_game_proto protoreflect.FileDescriptor

const file_core_network_protobuf_proto_src_game_proto_rawDesc = "" +
	"\n" +
	"*core/network/protobuf/proto_src/game.proto\x12\x05proto\"0\n" +
	"\n" +
	"MoveAction\x12\"\n" +
	"\x03dir\x18\x01 \x01(\x0e2\x10.proto.DirectionR\x03dir\"6\n" +
	"\vShootAction\x12'\n" +
	"\x06target\x18\x01 \x01(\v2\x0f.proto.PositionR\x06target\"m\n" +
	"\fPlayerAction\x12'\n" +
	"\x04move\x18\x01 \x01(\v2\x11.proto.MoveActionH\x00R\x04move\x12*\n" +
	"\x05shoot\x18\x02 \x01(\v2\x12.proto.ShootActionH\x00R\x05shootB\b\n" +
	"\x06action\"f\n" +
	"\vPlayerInput\x12:\n" +
	"\x0eplayer_actions\x18\x01 \x03(\v2\x13.proto.PlayerActionR\rplayerActions\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\rR\bplayerId\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"e\n" +
	"\vPlayerState\x12!\n" +
	"\x03pos\x18\x01 \x01(\v2\x0f.proto.PositionR\x03pos\x12\x16\n" +
	"\x06health\x18\x02 \x01(\x02R\x06health\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\rR\bplayerId\"_\n" +
	"\vBulletState\x12!\n" +
	"\x03pos\x18\x01 \x01(\v2\x0f.proto.PositionR\x03pos\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x02R\x04size\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\rR\aownerId\"\x83\x01\n" +
	"\n" +
	"WorldState\x12\x19\n" +
	"\btick_num\x18\x01 \x01(\rR\atickNum\x12,\n" +
	"\aplayers\x18\x02 \x03(\v2\x12.proto.PlayerStateR\aplayers\x12,\n" +
	"\abullets\x18\x03 \x03(\v2\x12.proto.BulletStateR\abullets\"-\n" +
	"\x0eConnectRequest\x12\x1b\n" +
	"\tgame_name\x18\x01 \x01(\tR\bgameName\")\n" +
	"\n" +
	"ConnectAck\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\"(\n" +
	"\tDeathNote\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\"6\n" +
	"\x10ReconnectRequest\x12\"\n" +
	"\rold_player_id\x18\x01 \x01(\rR\voldPlayerId\"\xef\x02\n" +
	"\vGameMessage\x12)\n" +
	"\x05world\x18\x01 \x01(\v2\x11.proto.WorldStateH\x00R\x05world\x127\n" +
	"\fplayer_input\x18\x02 \x01(\v2\x12.proto.PlayerInputH\x00R\vplayerInput\x12@\n" +
	"\x0fconnect_request\x18\x03 \x01(\v2\x15.proto.ConnectRequestH\x00R\x0econnectRequest\x12F\n" +
	"\x11reconnect_request\x18\x04 \x01(\v2\x17.proto.ReconnectRequestH\x00R\x10reconnectRequest\x124\n" +
	"\vconnect_ack\x18\x05 \x01(\v2\x11.proto.ConnectAckH\x00R\n" +
	"connectAck\x121\n" +
	"\n" +
	"death_note\x18\x06 \x01(\v2\x10.proto.DeathNoteH\x00R\tdeathNoteB\t\n" +
	"\apayload*<\n" +
	"\tDirection\x12\b\n" +
	"\x04NONE\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01\x12\t\n" +
	"\x05RIGHT\x10\x02\x12\x06\n" +
	"\x02UP\x10\x03\x12\b\n" +
	"\x04DOWN\x10\x04B\x18Z\x16core/network/protobuf/b\x06proto3"

var (
	file_core_network_protobuf_proto_src_game_proto_rawDescOnce sync.Once
	file_core_network_protobuf_proto_src_game_proto_rawDescData []byte
)

func file_core_network_protobuf_proto_src_game_proto_rawDescGZIP() []byte {
	file_core_network_protobuf_proto_src_game_proto_rawDescOnce.Do(func() {
		file_core_network_protobuf_proto_src_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_network_protobuf_proto_src_game_proto_rawDesc), len(file_core_network_protobuf_proto_src_game_proto_rawDesc)))
	})
	return file_core_network_protobuf_proto_src_game_proto_rawDescData
}

var file_core_network_protobuf_proto_src_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_network_protobuf_proto_src_game_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_core_network_protobuf_proto_src_game_proto_goTypes = []any{
	(Direction)(0),           // 0: proto.Direction
	(*MoveAction)(nil),       // 1: proto.MoveAction
	(*ShootAction)(nil),      // 2: proto.ShootAction
	(*PlayerAction)(nil),     // 3: proto.PlayerAction
	(*PlayerInput)(nil),      // 4: proto.PlayerInput
	(*Position)(nil),         // 5: proto.Position
	(*PlayerState)(nil),      // 6: proto.PlayerState
	(*BulletState)(nil),      // 7: proto.BulletState
	(*WorldState)(nil),       // 8: proto.WorldState
	(*ConnectRequest)(nil),   // 9: proto.ConnectRequest
	(*ConnectAck)(nil),       // 10: proto.ConnectAck
	(*DeathNote)(nil),        // 11: proto.DeathNote
	(*ReconnectRequest)(nil), // 12: proto.ReconnectRequest
	(*GameMessage)(nil),      // 13: proto.GameMessage
}
var file_core_network_protobuf_proto_src_game_proto_depIdxs = []int32{
	0,  // 0: proto.MoveAction.dir:type_name -> proto.Direction
	5,  // 1: proto.ShootAction.target:type_name -> proto.Position
	1,  // 2: proto.PlayerAction.move:type_name -> proto.MoveAction
	2,  // 3: proto.PlayerAction.shoot:type_name -> proto.ShootAction
	3,  // 4: proto.PlayerInput.player_actions:type_name -> proto.PlayerAction
	5,  // 5: proto.PlayerState.pos:type_name -> proto.Position
	5,  // 6: proto.BulletState.pos:type_name -> proto.Position
	6,  // 7: proto.WorldState.players:type_name -> proto.PlayerState
	7,  // 8: proto.WorldState.bullets:type_name -> proto.BulletState
	8,  // 9: proto.GameMessage.world:type_name -> proto.WorldState
	4,  // 10: proto.GameMessage.player_input:type_name -> proto.PlayerInput
	9,  // 11: proto.GameMessage.connect_request:type_name -> proto.ConnectRequest
	12, // 12: proto.GameMessage.reconnect_request:type_name -> proto.ReconnectRequest
	10, // 13: proto.GameMessage.connect_ack:type_name -> proto.ConnectAck
	11, // 14: proto.GameMessage.death_note:type_name -> proto.DeathNote
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_core_network_protobuf_proto_src_game_proto_init() }
func file_core_network_protobuf_proto_src_game_proto_init() {
	if File_core_network_protobuf_proto_src_game_proto != nil {
		return
	}
	file_core_network_protobuf_proto_src_game_proto_msgTypes[2].OneofWrappers = []any{
		(*PlayerAction_Move)(nil),
		(*PlayerAction_Shoot)(nil),
	}
	file_core_network_protobuf_proto_src_game_proto_msgTypes[12].OneofWrappers = []any{
		(*GameMessage_World)(nil),
		(*GameMessage_PlayerInput)(nil),
		(*GameMessage_ConnectRequest)(nil),
		(*GameMessage_ReconnectRequest)(nil),
		(*GameMessage_ConnectAck)(nil),
		(*GameMessage_DeathNote)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_network_protobuf_proto_src_game_proto_rawDesc), len(file_core_network_protobuf_proto_src_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_network_protobuf_proto_src_game_proto_goTypes,
		DependencyIndexes: file_core_network_protobuf_proto_src_game_proto_depIdxs,
		EnumInfos:         file_core_network_protobuf_proto_src_game_proto_enumTypes,
		MessageInfos:      file_core_network_protobuf_proto_src_game_proto_msgTypes,
	}.Build()
	File_core_network_protobuf_proto_src_game_proto = out.File
	file_core_network_protobuf_proto_src_game_proto_goTypes = nil
	file_core_network_protobuf_proto_src_game_proto_depIdxs = nil
}
