// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto_src/game.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_NONE  Direction = 0
	Direction_LEFT  Direction = 1
	Direction_RIGHT Direction = 2
	Direction_UP    Direction = 3
	Direction_DOWN  Direction = 4
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "NONE",
		1: "LEFT",
		2: "RIGHT",
		3: "UP",
		4: "DOWN",
	}
	Direction_value = map[string]int32{
		"NONE":  0,
		"LEFT":  1,
		"RIGHT": 2,
		"UP":    3,
		"DOWN":  4,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_src_game_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_proto_src_game_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_proto_src_game_proto_rawDescGZIP(), []int{0}
}

type MoveAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vert          Direction              `protobuf:"varint,1,opt,name=vert,proto3,enum=proto.Direction" json:"vert,omitempty"`
	Hori          Direction              `protobuf:"varint,2,opt,name=hori,proto3,enum=proto.Direction" json:"hori,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveAction) Reset() {
	*x = MoveAction{}
	mi := &file_proto_src_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveAction) ProtoMessage() {}

func (x *MoveAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveAction.ProtoReflect.Descriptor instead.
func (*MoveAction) Descriptor() ([]byte, []int) {
	return file_proto_src_game_proto_rawDescGZIP(), []int{0}
}

func (x *MoveAction) GetVert() Direction {
	if x != nil {
		return x.Vert
	}
	return Direction_NONE
}

func (x *MoveAction) GetHori() Direction {
	if x != nil {
		return x.Hori
	}
	return Direction_NONE
}

type ShootAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shoot target coordinates
	Pos           *Position `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShootAction) Reset() {
	*x = ShootAction{}
	mi := &file_proto_src_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShootAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootAction) ProtoMessage() {}

func (x *ShootAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootAction.ProtoReflect.Descriptor instead.
func (*ShootAction) Descriptor() ([]byte, []int) {
	return file_proto_src_game_proto_rawDescGZIP(), []int{1}
}

func (x *ShootAction) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

type PlayerAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*PlayerAction_Move
	//	*PlayerAction_Shoot
	Action        isPlayerAction_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	mi := &file_proto_src_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_proto_src_game_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerAction) GetAction() isPlayerAction_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *PlayerAction) GetMove() *MoveAction {
	if x != nil {
		if x, ok := x.Action.(*PlayerAction_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *PlayerAction) GetShoot() *ShootAction {
	if x != nil {
		if x, ok := x.Action.(*PlayerAction_Shoot); ok {
			return x.Shoot
		}
	}
	return nil
}

type isPlayerAction_Action interface {
	isPlayerAction_Action()
}

type PlayerAction_Move struct {
	Move *MoveAction `protobuf:"bytes,1,opt,name=move,proto3,oneof"`
}

type PlayerAction_Shoot struct {
	Shoot *ShootAction `protobuf:"bytes,2,opt,name=shoot,proto3,oneof"`
}

func (*PlayerAction_Move) isPlayerAction_Action() {}

func (*PlayerAction_Shoot) isPlayerAction_Action() {}

type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerActions []*PlayerAction        `protobuf:"bytes,1,rep,name=player_actions,json=playerActions,proto3" json:"player_actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_proto_src_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_proto_src_game_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInput) GetPlayerActions() []*PlayerAction {
	if x != nil {
		return x.PlayerActions
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_proto_src_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_proto_src_game_proto_rawDescGZIP(), []int{4}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Position              `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Health        uint32                 `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_proto_src_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_proto_src_game_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerState) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PlayerState) GetHealth() uint32 {
	if x != nil {
		return x.Health
	}
	return 0
}

type BulletState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Position              `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Size          float32                `protobuf:"fixed32,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletState) Reset() {
	*x = BulletState{}
	mi := &file_proto_src_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletState) ProtoMessage() {}

func (x *BulletState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletState.ProtoReflect.Descriptor instead.
func (*BulletState) Descriptor() ([]byte, []int) {
	return file_proto_src_game_proto_rawDescGZIP(), []int{6}
}

func (x *BulletState) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *BulletState) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type WorldState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerState         `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Bullets       []*BulletState         `protobuf:"bytes,2,rep,name=bullets,proto3" json:"bullets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldState) Reset() {
	*x = WorldState{}
	mi := &file_proto_src_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldState) ProtoMessage() {}

func (x *WorldState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldState.ProtoReflect.Descriptor instead.
func (*WorldState) Descriptor() ([]byte, []int) {
	return file_proto_src_game_proto_rawDescGZIP(), []int{7}
}

func (x *WorldState) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *WorldState) GetBullets() []*BulletState {
	if x != nil {
		return x.Bullets
	}
	return nil
}

var File_proto_src_game_proto protoreflect.FileDescriptor

const file_proto_src_game_proto_rawDesc = "" +
	"\n" +
	"\x14proto_src/game.proto\x12\x05proto\"X\n" +
	"\n" +
	"MoveAction\x12$\n" +
	"\x04vert\x18\x01 \x01(\x0e2\x10.proto.DirectionR\x04vert\x12$\n" +
	"\x04hori\x18\x02 \x01(\x0e2\x10.proto.DirectionR\x04hori\"0\n" +
	"\vShootAction\x12!\n" +
	"\x03pos\x18\x01 \x01(\v2\x0f.proto.PositionR\x03pos\"m\n" +
	"\fPlayerAction\x12'\n" +
	"\x04move\x18\x01 \x01(\v2\x11.proto.MoveActionH\x00R\x04move\x12*\n" +
	"\x05shoot\x18\x02 \x01(\v2\x12.proto.ShootActionH\x00R\x05shootB\b\n" +
	"\x06action\"I\n" +
	"\vPlayerInput\x12:\n" +
	"\x0eplayer_actions\x18\x01 \x03(\v2\x13.proto.PlayerActionR\rplayerActions\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"H\n" +
	"\vPlayerState\x12!\n" +
	"\x03pos\x18\x01 \x01(\v2\x0f.proto.PositionR\x03pos\x12\x16\n" +
	"\x06health\x18\x02 \x01(\rR\x06health\"D\n" +
	"\vBulletState\x12!\n" +
	"\x03pos\x18\x01 \x01(\v2\x0f.proto.PositionR\x03pos\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x02R\x04size\"h\n" +
	"\n" +
	"WorldState\x12,\n" +
	"\aplayers\x18\x01 \x03(\v2\x12.proto.PlayerStateR\aplayers\x12,\n" +
	"\abullets\x18\x02 \x03(\v2\x12.proto.BulletStateR\abullets*<\n" +
	"\tDirection\x12\b\n" +
	"\x04NONE\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01\x12\t\n" +
	"\x05RIGHT\x10\x02\x12\x06\n" +
	"\x02UP\x10\x03\x12\b\n" +
	"\x04DOWN\x10\x04B\x10Z\x0ecore/protobuf/b\x06proto3"

var (
	file_proto_src_game_proto_rawDescOnce sync.Once
	file_proto_src_game_proto_rawDescData []byte
)

func file_proto_src_game_proto_rawDescGZIP() []byte {
	file_proto_src_game_proto_rawDescOnce.Do(func() {
		file_proto_src_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_src_game_proto_rawDesc), len(file_proto_src_game_proto_rawDesc)))
	})
	return file_proto_src_game_proto_rawDescData
}

var file_proto_src_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_src_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_src_game_proto_goTypes = []any{
	(Direction)(0),       // 0: proto.Direction
	(*MoveAction)(nil),   // 1: proto.MoveAction
	(*ShootAction)(nil),  // 2: proto.ShootAction
	(*PlayerAction)(nil), // 3: proto.PlayerAction
	(*PlayerInput)(nil),  // 4: proto.PlayerInput
	(*Position)(nil),     // 5: proto.Position
	(*PlayerState)(nil),  // 6: proto.PlayerState
	(*BulletState)(nil),  // 7: proto.BulletState
	(*WorldState)(nil),   // 8: proto.WorldState
}
var file_proto_src_game_proto_depIdxs = []int32{
	0,  // 0: proto.MoveAction.vert:type_name -> proto.Direction
	0,  // 1: proto.MoveAction.hori:type_name -> proto.Direction
	5,  // 2: proto.ShootAction.pos:type_name -> proto.Position
	1,  // 3: proto.PlayerAction.move:type_name -> proto.MoveAction
	2,  // 4: proto.PlayerAction.shoot:type_name -> proto.ShootAction
	3,  // 5: proto.PlayerInput.player_actions:type_name -> proto.PlayerAction
	5,  // 6: proto.PlayerState.pos:type_name -> proto.Position
	5,  // 7: proto.BulletState.pos:type_name -> proto.Position
	6,  // 8: proto.WorldState.players:type_name -> proto.PlayerState
	7,  // 9: proto.WorldState.bullets:type_name -> proto.BulletState
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_src_game_proto_init() }
func file_proto_src_game_proto_init() {
	if File_proto_src_game_proto != nil {
		return
	}
	file_proto_src_game_proto_msgTypes[2].OneofWrappers = []any{
		(*PlayerAction_Move)(nil),
		(*PlayerAction_Shoot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_src_game_proto_rawDesc), len(file_proto_src_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_src_game_proto_goTypes,
		DependencyIndexes: file_proto_src_game_proto_depIdxs,
		EnumInfos:         file_proto_src_game_proto_enumTypes,
		MessageInfos:      file_proto_src_game_proto_msgTypes,
	}.Build()
	File_proto_src_game_proto = out.File
	file_proto_src_game_proto_goTypes = nil
	file_proto_src_game_proto_depIdxs = nil
}
